#!/usr/local/bin/zsh
# This hook is sourced after every virtualenv is activated.
PS1="$_OLD_VIRTUAL_PS1"
_OLD_PROMPT="$PROMPT"
PROMPT="%{${fg[green]}%}env:%{${fg[red]}%}`basename \"$VIRTUAL_ENV\"`%{${reset_color}%} $PROMPT"

