#!/usr/local/bin/zsh

# This hook is sourced after every virtualenv is activated.

# ZSH
PS1="$_OLD_VIRTUAL_PS1"
_OLD_PROMPT="$PROMPT"
PROMPT="%{${fg[green]}%}pyenv:%{${fg[red]}%}`basename \"$VIRTUAL_ENV\"`%{${reset_color}%} $PROMPT"

# BASH
# OLD_PS1="$_OLD_VIRTUAL_PS1"
# export PS1="\[\e[32m\]pyenv:\[\e[0m\]\[\e[31m\]`basename \"$VIRTUAL_ENV\"`\[\e[0m\] $OLD_PS1"

