# General

if [[ "$OSTYPE" == "linux-gnu" ]]; then
		alias ls="ls --color=auto"
else
		alias ls="ls -G"
fi

alias ll="ls -hlAG"
alias rm="rm -i"
alias cp="cp -i"
alias grep="grep --color=auto"
alias egrep="egrep --color=auto"
alias fgrep="fgrep --color=auto"

# Tags
alias ssctags="git ls-files starscream shopify config | /usr/local/opt/universal-ctags/bin/ctags -f tmp/tags --tag-relative=yes --extras=+f -L-"
